//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CustomRes {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Custom {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Custom() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RapidDoc.Resources.Custom.Custom", typeof(Custom).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Активы.
        /// </summary>
        public static string Assets {
            get {
                return ResourceManager.GetString("Assets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Города.
        /// </summary>
        public static string Country {
            get {
                return ResourceManager.GetString("Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Список ip адресов.
        /// </summary>
        public static string IpList {
            get {
                return ResourceManager.GetString("IpList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Номенклатурное дело.
        /// </summary>
        public static string ItemCause {
            get {
                return ResourceManager.GetString("ItemCause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Организации.
        /// </summary>
        public static string Organization {
            get {
                return ResourceManager.GetString("Organization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Проекты.
        /// </summary>
        public static string Projects {
            get {
                return ResourceManager.GetString("Projects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Протокольные папки.
        /// </summary>
        public static string ProtocolFolders {
            get {
                return ResourceManager.GetString("ProtocolFolders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вопрос обращения.
        /// </summary>
        public static string QuestionRequest {
            get {
                return ResourceManager.GetString("QuestionRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Причины обращений.
        /// </summary>
        public static string ReasonRequest {
            get {
                return ResourceManager.GetString("ReasonRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Текст запроса.
        /// </summary>
        public static string RequestText {
            get {
                return ResourceManager.GetString("RequestText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Расписание задач.
        /// </summary>
        public static string TaskSchedule {
            get {
                return ResourceManager.GetString("TaskSchedule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Справочник МРП.
        /// </summary>
        public static string TripMRP {
            get {
                return ResourceManager.GetString("TripMRP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нормы коммандировок.
        /// </summary>
        public static string TripSettings {
            get {
                return ResourceManager.GetString("TripSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пользователи.
        /// </summary>
        public static string Users {
            get {
                return ResourceManager.GetString("Users", resourceCulture);
            }
        }
    }
}
